version: "3"
services:
  frontend:
    build: ./client
    networks:
      - mosh-net
  backend:
    build: ./server
    networks:
      - mosh-net
  revproxy:
    build: ./proxy
    networks:
      - mosh-net
    ports:
      - "80:80"
networks:
  mosh-net:
